### ISSUE TITLE
Allow to compare df ignoring the order

### ISSUE THREAD

**Issue by azachar** [MrPowers/chispa#10]
Hi there, 

Thank you for the effort on this library. Perhaps it would be great to add an extra assert that would ignore the order in dataframe.

Some of the functions, for example df.dropDuplicates() are unpredictable in order. It would be great to have something that would just ignore the order, or order all record by a given column...

Thank you for any consideration!

Good luck!

**Comment by MrPowers** [comment]
@azachar - here's how you can compare DataFrames, ignoring the row order (see [this commit](https://github.com/MrPowers/chispa/commit/e2469ef4bab509b50f6dd628734b45b468132e1b)):

```python
assert_df_equality(df1, df2, transforms=[lambda df: df.sort(df.columns)])
```

Here's how you can compare two DataFrames, ignoring the column order:

```python
assert_df_equality(df1, df2, transforms=[lambda df: df.select(sorted(df.columns))])
```

Let me know if that solves your issue, thanks!

**Comment by azachar** [comment]
Nice! Thank you @MrPowers. 

Would you consider also some self speaking wrapper methods to hide that "sugar" code?

Cheers, Andrej

**Comment by MrPowers** [comment]
@azachar - I added additional options to `assert_df_equality`:

```python
def assert_df_equality(df1, df2, ignore_nullable=False, transforms=None, allow_nan_equality=False, ignore_column_order=False, ignore_row_order=False)
```

Let me know if those will work for you ;)

Thanks again for the suggestions!
