### ISSUE TITLE
bug: Build failure after #80

### ISSUE THREAD

**Issue by SemyonSinchenko** [MrPowers/chispa#107]
https://github.com/MrPowers/chispa/actions/runs/9961761839/job/27524024374

**Comment by SemyonSinchenko** [comment]
@fpgmaas May you take a look, please?

**Comment by fpgmaas** [comment]
I will create a hotfix PR. We should add  [`poetry lock --check`](https://python-poetry.org/docs/cli/#options-11) to the CI/CD pipeline to prevent this in the future.
