### ISSUE TITLE
The repository is missing a release pipeline

### ISSUE THREAD

**Issue by fpgmaas** [MrPowers/chispa#131]
**Is your feature request related to a problem? Please describe.**

The repository currently does not contain a release pipeline. We should add a method to publish the project to PyPI whenever a new release is created on Github.

**Comment by MrPowers** [comment]
Yea, definitely agree with this, can I assign this one to you @fpgmaas?

**Comment by fpgmaas** [comment]
@MrPowers Yes, I opened a PR for this! In order to get this to work, could you create a repository secret called `PYPI_TOKEN` on the repository, that is scoped to the `chispa` project?
