### ISSUE TITLE
assert_df_equality fails when comparing nan values

### ISSUE THREAD

**Issue by melsyt** [MrPowers/chispa#14]
Hello, 

First of all, thank you for this great package! It's really making my test code cleaner. 

One issue I've encountered is that when I perform `assert_df_equality()` on two dataframes where each contains a row with NaN values, the test fails. 
![image](https://user-images.githubusercontent.com/42623406/112520291-9e349880-8d71-11eb-9bb9-760419ae3c00.png)

I can see why it would fail as `float("nan") == float("nan")` evaluates to `False`. However, if I convert the dataframes to pandas df first, then use `pd.testing.assert_frames_equal`, the test passes. It would be awesome if `assert_df_equality` can handle NaN cases as well. 

Thanks!

**Comment by MrPowers** [comment]
@melsyt - thanks for reporting this!

[Here's a fix](https://github.com/MrPowers/chispa/pull/16) that'll let you do `assert_df_equality(df1, df2, allow_nan_equality=True)` to consider the nan values equal.  Can you take a look and let me know if this looks good, thanks!

**Comment by melsyt** [comment]
@MrPowers Thanks for addressing this so quickly! The new argument works perfectly!

**Comment by MrPowers** [comment]
@melsyt - thanks again for reporting this issue - with details that made the request easy to understand ;)

Fixed the bug & published a new release, see version 0.8.0.

Feel free to report any other issues you have with the lib and I'll make sure to get them fixed!

**Comment by melsyt** [comment]
Thank YOU and glad to be of help! :)
