### ISSUE TITLE
Misleading coloring after failing assert

### ISSUE THREAD

**Issue by evgenii-brovkin** [MrPowers/chispa#5]
Hi, I'm using chispa for tests. I found that it paints some columns red in a report, even if they are not incorrect. Look at the example below. I have **size_cd** and **retail_week** columns reshufled, which is causing assertion error. But chispa also paints red all other columns which have different **nullable** option even though I'm using _ignore nullable_ parameter.

I think it would be better to paint such columns blue. Right now it feels like chispa does not work as intended with _ignore nullable_ parameter.

![pic](https://user-images.githubusercontent.com/59195462/97904510-a869e200-1d51-11eb-960b-f7e95e64b453.png)

**Comment by MrPowers** [comment]
@evgenii-brovkin - thank you for reporting this bug, I fixed it in [this commit](https://github.com/MrPowers/chispa/commit/4db4ddc18732254d04123a32b983061601fa891a).

Sorry for the delay in getting this fixed.  I will make a new release now, so PyPi will have this fix.  Your high quality bug report helped me easily identify the issue and fix the problem for you, and other user.  Thank you and let me know if there is any other way I can improve this library.
