### ISSUE TITLE
pkg_resources is deprecated, prettytable produces warning

### ISSUE THREAD

**Issue by ethnhll** [MrPowers/chispa#58]
using `assert_df_equality` produces a warning in the console about pkg_resources being deprecated.

```python
======================================================================================= warnings summary ========================================================================================
.venv/lib/python3.9/site-packages/pkg_resources/__init__.py:121
  /Users/ethnhll/Projects/dsc-publish/.venv/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================= 1 passed, 1 warning in 11.76s =================================================================================

```

Looking at the code where `pkg_resources` is referenced, it seems like it is not currently in use.

https://github.com/MrPowers/chispa/blob/2f1de2690e480e19e492ffe87937db50c4da4f33/chispa/prettytable.py#L44

I'm not familiar enough with the build processes at play for this project so I can't say for sure that removing the dependency on pkg_resources in `prettytable.py` won't have unintended side effects, but I can open a PR that removes it.

**Comment by MrPowers** [comment]
This was merged.
